// Bakes an alpha-weighted average color per tech icon into
// src/lib/techColors.ts. Run with: bun scripts/generate-tech-colors.ts
// Near-white pixels are ignored so icons on white backgrounds keep their
// brand color instead of averaging toward white.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PNG } from 'pngjs'

const HERE = fileURLToPath(new URL('.', import.meta.url))
const ICONS_DIR = join(HERE, '../public/icons/tech')
const OUT_FILE = join(HERE, '../src/lib/techColors.ts')

function averageColor(file: string): string | null {
  const png = PNG.sync.read(readFileSync(file))
  let r = 0
  let g = 0
  let b = 0
  let weight = 0
  const pass = (ignoreWhite: boolean) => {
    r = g = b = weight = 0
    for (let i = 0; i < png.data.length; i += 4) {
      const a = png.data[i + 3]
      if (a < 25) continue
      const pr = png.data[i]
      const pg = png.data[i + 1]
      const pb = png.data[i + 2]
      if (ignoreWhite && pr > 235 && pg > 235 && pb > 235) continue
      r += pr * a
      g += pg * a
      b += pb * a
      weight += a
    }
  }
  pass(true)
  if (weight === 0) pass(false)
  if (weight === 0) return null
  const hex = (v: number) =>
    Math.round(v / weight)
      .toString(16)
      .padStart(2, '0')
  return `#${hex(r)}${hex(g)}${hex(b)}`
}

const entries: string[] = []
for (const file of readdirSync(ICONS_DIR).sort()) {
  if (!file.endsWith('.png')) continue
  const color = averageColor(join(ICONS_DIR, file))
  if (color) entries.push(`  ${file.replace('.png', '')}: '${color}',`)
}

writeFileSync(
  OUT_FILE,
  `// Generated by scripts/generate-tech-colors.ts - do not edit by hand.
export const techColors: Record<string, string> = {
${entries.join('\n')}
}
`,
)
console.log(`Wrote ${entries.length} colors to ${OUT_FILE}`)
